### ISSUE TITLE
Where should I put my model

### ISSUE THREAD

**Issue by ShadAdman** [nex3z/tflite-object-detection-demo#1]
Hi. I was wondering if this project is working?
this project has a clean kotlin code

**Comment by nex3z** [comment]
Yes, it works. The model is trained and converted as in [eager_few_shot_od_training_tflite.ipynb](https://github.com/tensorflow/models/blob/master/research/object_detection/colab_tutorials/eager_few_shot_od_training_tflite.ipynb). Then copy the `model.tflite` to `/app/src/main/assets`, build and run the app. 

Now you have a rubber Ducky detector.

![Screenshot_2021-05-11-23-13-08-691_com nex3z examples tflite detect](https://user-images.githubusercontent.com/5645004/117840269-9643a000-b2ae-11eb-8cc7-e7aa47eb1d2c.jpg)
